### ISSUE TITLE
Assertion Fail

### ISSUE THREAD

**Issue by Snugug** [at-import/node-sass-import-once#1]
When running (through Gulp) often will get, getting the following error:

```
Assertion failed: (handle->flags & UV_CLOSING), function uv__finish_close, file ../deps/uv/src/unix/core.c, line 209.
[1]    15739 abort      gulp
```

**Comment by Snugug** [comment]
@Jakobo @chriseppstein @xzyfer @mgreter @akhleung thoughts?

**Comment by thecodedrift** [comment]
Reference: https://github.com/sass/node-sass/issues/713 (known issue)

**Comment by Snugug** [comment]
Bah, I guess my brain is too fried. Of course I should have checked the issue queue for both of these things issues before posting them. Thanks!
