### ISSUE TITLE
importing .js files as modules rather than parsing contents as JSON

### ISSUE THREAD

**Issue by oliverturner** [at-import/node-sass-import-once#10]
I'd love to be able to import JS modules that export their payload as an object or JSON... Is there any interest in on your side in me submitting a PR that implements this?

**Comment by oliverturner** [comment]
FWIW I have a working prototype

**Comment by Snugug** [comment]
Have you tried it yet? I added this functionality in https://github.com/at-import/node-sass-import-once/issues/3

**Comment by oliverturner** [comment]
I did... 

Happy to be corrected, but it looked as though there's no distinction made between loading  from `.js` vs from `.json`: the importer simply consumes the stringified contents of the file.

What I want is to do work in the target `.js` file and then use the value from `module.exports` as the payload. This currently causes the programming to fail since it's simply reading in the text content of the file, not parsing it.

**Comment by oliverturner** [comment]
Also, this tool rocks _hard_ in every other respect: thanks for providing!

**Comment by Snugug** [comment]
As long as it supports both usecases, open up a PR

**Comment by oliverturner** [comment]
ok, so can I just check that the current implementation supports .js files of the following shape?

```
// test.js
{
  "default": {
    "small": {
      "family": "base",
      "size":   "14px"
    },

    "medium": {
      "family": "body",
      "size":   "14px"
    },

    "large": {
      "family": "body",
      "size":   "14px"
    }
  }
}
```

**Comment by Snugug** [comment]
Yup

**Comment by oliverturner** [comment]
ok thanks.

Will add support, but can I just ask why not simply encourage users to supply these configs as `.json`?

**Comment by Snugug** [comment]
I had a specific request for this from a coworker

**Comment by oliverturner** [comment]
Ah... ok. Thanks for letting me know. 

I might refrain from making the PR in that case: I can't think of an elegant way to allow JSON  with a file extension of `.js` and actual JS to coexist when all I have is the extension to determine the difference.
