### ISSUE TITLE
Better default to true for most options

### ISSUE THREAD

**Issue by macmladen** [at-import/node-sass-import-once#14]
If someone is already including this module that is because one needs including paths **on** by default, so I'd suggest:

``` js
var sass = require('node-sass');,
    importOnce = require('node-sass-import-once');

sass.render({
  file: scss_filename,
  importer: importOnce,
  importOnce: {
    index: false,
    css: true,
    bower: true,
    node: true
  }
});
```

**Comment by Snugug** [comment]
The only default should be importing things once. The other options (CSS, Index, Bower, Node) are all optional modules to turn on/off, and as there's a perf overhead for enabling them, I don't think they should be on by default.
