### ISSUE TITLE
globbing solution

### ISSUE THREAD

**Issue by JohnAlbin** [at-import/node-sass-import-once#16]
Since node-sass can only have one importer, we can't have one importer doing "import once" and another one doing "globbing".

What's the solution here? Stop using globbing? Or add it to node-sass-import-once?

``` scss
@import 'components/*';
```

**Comment by JohnAlbin** [comment]
Woah. Totally missed that you _can_ have mulitple importers. https://github.com/sass/node-sass#importer--v200---experimental

hat tip @robloach

**Comment by RobLoach** [comment]
:+1: 

Being implicit with your includes is usually better, still. But, if it works, saves you time, money, and life, then :+1: .

**Comment by Snugug** [comment]
FWIW, the solution is the `_index` import.
