### ISSUE TITLE
Multiple failures with node-sass 3.4.1

### ISSUE THREAD

**Issue by JohnAlbin** [at-import/node-sass-import-once#18]
I never used this module with previous versions of node-sass, but under node-sass 3.4, we have multiple failures:
- FAILS to import files only once.
- FAILS to import relative files. The expected Ruby behavior is that it will look in the current file's directory for the import before looking in the include paths. E.g. if `breakpoint/_parsers.scss` imports `"parser/single"`, it should look for it in the breakpoint directory.

I don't see a test for the second failure, so we'll need to add one.

There's actually 8 other test failure, but they may be cascading failures since the very first test fails.

**Comment by JohnAlbin** [comment]
In node-sass 3.4, the "prev" argument is the “the path in import as-is, which libsass encountered”. If the "prev" file was not @import'ed and just loaded into node-sass, then the "prev" argument is the full path to the file.

It looks like node-sass-import-once is only looking at the prev argument when it is a full path. But that is wrong. If the "prev" import was "folder/file", it needs to look in the "folder" where it found "file".

I just tested Ruby Sass and when it encounters an `@import "somefile";` it looks for the "somefile" in this order:
1. The same directory of the file that had the `@import`.
2. The project root (if Sass was pointed at a directory to render)
3. Import paths

It looks like node-sass is taking care that 2 is added to the top of the import paths. And while node-sass correctly does 1, node-sass-import-once is ignoring 1.

**Comment by JohnAlbin** [comment]
Some of this will be fixed with https://github.com/sass/node-sass/pull/1220 , maybe? Can't test until the bindings are rebuilt with the new node-sass 3.4.2 release.

**Comment by Snugug** [comment]
I'm betting this is the same issue as a lot of this code comes from work Chris has done for Eyeglass and if it's broken for him, it's broken for me. Let's see what 3.4.2 brings

**Comment by yoannisj** [comment]
Apparently, in eyeglass this was fixed with the new release of node-sass-3.4.2: [sass-eyeglass/eyeglass#73](https://github.com/sass-eyeglass/eyeglass/issues/73)

Might be just a matter of updating the node-sass dependency to 3.4.2

**Comment by JohnAlbin** [comment]
> Might be just a matter of updating the node-sass dependency to 3.4.2

No need. The current package.json has `"node-sass": "^3.0.0-beta.5"` so it will pick up the latest 3.x version of node-sass.

It looks like node-sass-import-once works again now that node-sass 3.4.2 is out.

However, node-sass-import-once _tests_ still need to be fixed as node-sass' compilation has changed slightly. I already opened https://github.com/at-import/node-sass-import-once/pull/19 to fix them.
