### ISSUE TITLE
Doesn't work on OSX

### ISSUE THREAD

**Issue by rbarilani** [at-import/node-sass-import-once#27]
Apparently the importer doesn't work on OSX.

Fails with nested relative imports.

Probably related to #24

**Comment by Snugug** [comment]
Was this resolved by https://github.com/at-import/node-sass-import-once/pull/26?

**Comment by JohnAlbin** [comment]
FYI, I've been using node-sass-import-once without issue on OSX for months.

[edit: to be clear, node-sass was broken for a while there causing this module to not work, but that wasn't OSX-specific.]
