### ISSUE TITLE
extract-text-webpack-plugin

### ISSUE THREAD

**Issue by seeden** [at-import/node-sass-import-once#29]
Hi

Do you have any ideas how to use it with extract-text-webpack-plugin ?
I have tons of duplicities because import.

Thank you for any help

**Comment by seeden** [comment]
forget it ... I have started to use css-modules with composes: col-sm-4 from global;

**Comment by wzup** [comment]
@seeden and how do you import `@media` queries with `composes`?

**Comment by seeden** [comment]
@wzup I am using bootstrap-scss as global css with media queries and it is working

**Comment by freddyrangel** [comment]
I'd like to reopen this issue because we're seeing something very similar with webpack and sass. How do we use this with webpack? I've been trying something like this and it doesn't seem to work:

```
  sassLoader: {
    includePaths: [paths.sassPath, paths.appNodeModules, bourbonPaths, neatPaths],
    importer: require('node-sass-import-once'),
    importOnce: {
      index: true,
      css: true,
      bower: false
    }
  },
```

```
test: /\.scss$/,
loader: ExtractTextPlugin.extract(`css!resolve-url!sass`)
```

**Comment by faceyspacey** [comment]
any one find out how to do this in webpack?
