### ISSUE TITLE
Doesn't work with gulp: this is undefined

### ISSUE THREAD

**Issue by rootical** [at-import/node-sass-import-once#5]
Hi, i would really love to start using the module, but... Relates to #4.
I have node sass  "version": "3.0.0-beta.7", "libsass": "3.2.0-beta.6" and the latest gulp-sass. Here is how i pass it to the options:

``` javascript
.pipe($.sass({
            style: 'expanded',
            importer: importOnce
        }))
```

The error: 

```

/Users/vadzim/DEV/Projects/WKL/wkcss/node_modules/node-sass-import-once/index.js:275
  if (!this.options.importOnce) {
           ^
TypeError: Cannot read property 'options' of undefined
    at importer (/Users/vadzim/DEV/Projects/WKL/wkcss/node_modules/node-sass-import-once/index.js:275:12)
    at options.importer (/Users/vadzim/DEV/Projects/WKL/wkcss/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:212:20)

```

Thanks for your work.

**Comment by rootical** [comment]
Btw, @mcsagittarius suggestion seems to work. Although i started getting the whole output of my scss which is quite huge and annoying.

```
            importer: function(uri, prev, done) {
                importOnce.call({options: {}}, uri, prev, done);
            }
```

**Comment by Snugug** [comment]
Please try re-installing both `gulp-sass` and `node-sass-import-once`. On a clean install of both (physically remove them from your `node_modules` folder), this works fine `gulp-sass 2.0.0-alpha.1`

**Comment by rootical** [comment]
Looks like the problem was in gulp-sass, since I had the 1.3.3 version. After replacing with suggested "2.0.0-alpha.1" it started working.
Thank you a lot.
